apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  labels:
    app.kubernetes.io/component: solr
spec:
  serviceName: solr-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: solr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: solr
    spec:
      securityContext:
        fsGroup: 8983
      containers:
        - name: solr
          image: ghcr.io/nlnwa/solr:poc
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8983
          securityContext:
            runAsUser: 8983
            runAsGroup: 8983
            runAsNonRoot: true
          env:
            - name: SOLR_PORT_NUMBER
              value: "8983"
            # SOLR_HEAP sets the -Xmx and -Xms to the same value
            # If you want to configure them differently, use SOLR_JAVA_MEM
            # instead and unset SOLR_HEAP.
            - name: SOLR_HEAP
              value: "1024m"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          livenessProbe:
            initialDelaySeconds: 40
            timeoutSeconds: 15
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  curl --silent --connect-timeout 15000 http://localhost:${SOLR_PORT_NUMBER}/api/node/properties
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 15
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  curl --silent --connect-timeout 15000 http://localhost:${SOLR_PORT_NUMBER}/api/node/properties
