apiVersion: v1
kind: Service
metadata:
  name: solr
  labels:
    app.kubernetes.io/component: solr
spec:
  type: ClusterIP
  ports:
    - name: tcp-client
      port: 8983
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: solr
