apiVersion: batch/v1
kind: Job
metadata:
  name: warc-indexer
spec:
  template:
    spec:
      containers:
        - name: warc-indexer
          args:
            - /mnt/warcs/veidemann/validwarcs/noall
          env:
            - name: INDEXER_CUSTOM
              value: "--collection noall"
          volumeMounts:
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/noall/noall_2019
              subPath: veidemann/validwarcs/noall/noall_2019
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/noall/noall_2020
              subPath: veidemann/validwarcs/noall/noall_2020
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/noall/noall_2021
              subPath: veidemann/validwarcs/noall/noall_2021
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/noall/noall_2022
              subPath: veidemann/validwarcs/noall/noall_2022
