apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - pv.yaml
  - pvc.yaml
  - ../../base/solrwayback

configMapGenerator:
  - name: properties
    files:
      - solrwayback.properties
      - solrwaybackweb.properties

patches:
  - path: patch.yaml
