apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warcs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: warcs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
