apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warc-index-tmp
spec:
  storageClassName: glusterfs
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
