apiVersion: batch/v1
kind: Job
metadata:
  name: warc-indexer
spec:
  template:
    spec:
      containers:
        - name: warc-indexer
          args:
            - /mnt/warcs/veidemann/validwarcs/samisk
          env:
            - name: INDEXER_CUSTOM
              value: "--collection samisk"
          volumeMounts:
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/samisk/samisk_2020
              subPath: veidemann/validwarcs/samisk/samisk_2020
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/samisk/samisk_2021
              subPath: veidemann/validwarcs/samisk/samisk_2021
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/samisk/samisk_2022
              subPath: veidemann/validwarcs/samisk/samisk_2022
            - name: warcs
              mountPath: /mnt/warcs/veidemann/validwarcs/samisk/samisk_2023
              subPath: veidemann/validwarcs/samisk/samisk_2023
      volumes:
        - name: warcs
          persistentVolumeClaim:
            claimName: nettarkivet-3
            readOnly: true