apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: loke-n1
      initContainers:
      # Give `solr` user (id 8983) permissions to data dir
      - name: volume-permissions
        image: busybox
        command:
        - /bin/sh
        args:
         - -ec
         - |
           mkdir -p /mnt/data/workshop-2023
           chown 8983:8983 /mnt/data/workshop-2023
        volumeMounts:
        - name: data
          mountPath: /mnt/data
      containers:
        - name: solr
          volumeMounts:
            # Mount the volume into the data dir as specified by
            # /opt/solr/server/solr/mycores/netarchivebuilder/core.properties
            - name: data
              mountPath: /opt/solr/server/solr/mycores/netarchivebuilder/netarchivebuilder_data
              subPath: workshop-2023
          env:
            # SOLR_HEAP sets the -Xmx and -Xms to the same value
            # If you want to configure them differently, use SOLR_JAVA_MEM
            # instead and unset SOLR_HEAP.
            - name: SOLR_HEAP
              value: "16384m"          
          resources:
            requests:
              memory: "50G"
              cpu: "10"
            limits:
              memory: "50G"
              cpu: "10"
