apiVersion: apps/v1
kind: Deployment
metadata:
  name: solrwayback
  labels:
    app.kubernetes.io/name: solrwayback
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: solrwayback
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solrwayback
    spec:
      containers:
        - name: tomcat
          image: solrwayback:local
          ports:
            - name: http
              containerPort: 8080
          # TODO: Add liveness and readiness probes
          # livenessProbe:
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   failureThreshold: 6
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 3
          #   successThreshold: 1 
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "300m"
