apiVersion: v1
kind: Service
metadata:
  name: solrwayback
  labels:
    app.kubernetes.io/name: solrwayback
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/name: solrwayback
