name: "Test"

on:
  push:

jobs:
    build-docker-image:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Build SolrWayback Docker image
              run: docker build --tag solrwayback .
