name: Test

on:
  push:

jobs:
  test-ensure-arguments-in-sync:
    name: Test ensure arguments in sync
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --requirement test-requirements.txt
      - name: Run test
        run: |
          pytest **/*.py
  ensure-arguments-in-sync:
    name: Ensure arguments in sync
    needs: test-ensure-arguments-in-sync
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Ensure arguments in sync
        run: |
          python ensure_arguments_in_sync.py
